services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-26.0.1}
    container_name: keycloak
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh show-config && /opt/keycloak/bin/kc.sh start --optimized"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      KC_LOG_CONSOLE_LEVEL: all
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: ${KC_DB:-postgres}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:9000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-keycloak}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-keycloak}
      POSTGRES_DB: ${PG_DATABASE:-keycloak}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_USER:-keycloak} -d ${PG_DATABASE:-keycloak} || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
