parent=keycloak.v3
darkMode=false
contentHashPattern=assets/.*
styles=css/noir-account.css

title=Example.com Account
description=Manage your Example.com account settings and security.
logo=/img/noir-logo.svg
logoUrl=https://examples-poc.example.com
favIcon=/img/noir-logo.svg
favIconType=image/svg+xml
