name: Keycloak Database Integration Tests
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      database:
        description: "Database to test"
        required: true
        type: choice
        options:
          - All
          - mssql
          - postgres
        default: "All"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-keycloak:
    name: Test Keycloak with ${{ matrix.database }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: ${{ fromJSON(github.event.inputs.database == 'All' && '["mssql", "postgres"]' || github.event.inputs.database == 'All' && '["mssql", "postgres"]' || '["' + github.event.inputs.database + '"]') }}
      fail-fast: false

    env:
      KC_DB: ${{ matrix.database }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Services
        run: make up

      - name: Run Tests
        run: |
          for i in {1..3}; do
            if make test; then
              exit 0
            fi
            echo "Test failed, retrying in 15 seconds... ($i/3)"
            sleep 15
          done
          echo "Tests failed after 3 attempts"
          exit 1

      - name: Stop & Clean Up
        run: make down
        if: always()
